### ISSUE TITLE
Disposable VMs don't work with mirage-firewall

### ISSUE THREAD

**Issue by talex5** [talex5/qubes-mirage-firewall#9] opened 2016-09-13 19:33 UTC
The qubes-mirage-firewall log shows:

```
INF [net] Client 26 (IP: 10.138.3.6) ready
WRN [net] Error connecting client domain 26: "Assert_failure client_eth.ml:29:2"
```

This is from:

```
let add_client t iface =
  let ip = iface#other_ip in
  assert (Ipaddr.V4.Prefix.mem ip t.prefix);
  ...
```

Indeed, the new client is on a different network:

```
[tal@dom0 ~]$ qubesdb-read -d mirage-firewall /qubes-ip
10.137.1.13
[tal@dom0 ~]$ qubesdb-read -d mirage-firewall /qubes-netmask
255.255.255.0
```

I'm not sure what Qubes expects us to do in this case.

(originally reported at http://roscidus.com/blog/blog/2016/01/01/a-unikernel-firewall-for-qubesos/#comment-2891819810)

**Comment by marmarek** [comment] 2016-09-14 08:48
Disposable VMs have IP address allocated from different pool on purpose. The `/qubes-ip` and `/qubes-netmask` entries are about firewallvm own IP, not a network for downstream VMs, so it's unrelated. Downstream interface should be treated as point-to-point interface, with a single host route to it.

**Comment by talex5** [comment] 2016-09-14 09:16
Thanks. Is there any way to tell the difference between a downstream client IP that isn't currently connected and an upstream IP address?

e.g. if I see a packet for `10.138.3.7` and that isn't currently one of my clients, should I send it to NetVM? Or is there some way to know that it's a client address and should be dropped? Currently the firewall allows you to write rules for "unconnected clients" (https://github.com/talex5/qubes-mirage-firewall/blob/master/client_eth.ml#L48).

**Comment by marmarek** [comment] 2016-09-14 09:28
You know what clients are connected currently - based on existing vif interfaces. If none match - that's not a valid downstream IP. There is no way (by design) to distinguish between invalid downstream IP from disconnected client IP. In Qubes 4.0 we even no longer put netvm-specific part in that IP (all addresses will be in `10.137.0.0/16` or `10.138.0.0/16`).

**Comment by talex5** [comment] 2016-09-25 15:44
OK, I've updated it to allow clients to have any IP address: https://github.com/talex5/qubes-mirage-firewall/commit/a7001a70d2f1f929323b7b53101b1638b60a6bc0

With this change:

- We no longer reject clients with unknown IP addresses.
- The `Unknown_client` classification is gone; we have no way to tell the difference between a client that isn't connected and an external address.
- We now consider every client to be on a point-to-point link and do not answer ARP requests on behalf of other clients. Clients should assume their netmask is 255.255.255.255 (and ignore `/qubes-netmask` - what is this for?).

This allows disposable VMs to connect to the firewall but for some reason they don't process any frames we send them initially (we get their ARP requests but they don't get our replies). Taking eth0 down in the disp VM, then bringing it back up (and re-adding the routes) allows it to work. Maybe something to do with the way disp VMs are suspended and resumed?

**Comment by marmarek** [comment] 2016-09-26 09:43
> We now consider every client to be on a point-to-point link and do not answer ARP requests on behalf of other clients. Clients should assume their netmask is 255.255.255.255 (and ignore /qubes-netmask - what is this for?).

`/qubes-netmask` is mostly legacy compatibility. Linux VMs only check its presence, but ignore content.

> This allows disposable VMs to connect to the firewall but for some reason they don't process any frames we send them initially (we get their ARP requests but they don't get our replies). Taking eth0 down in the disp VM, then bringing it back up (and re-adding the routes) allows it to work. Maybe something to do with the way disp VMs are suspended and resumed?

Maybe... I'd guess mirage vif backend driver doesn't handle domain suspend. To be honest I'm not sure how is it different from normal attach/detach.
As a workaround you can set netvm to none for DispVM template (`fedora-23-dvm` or other *-dvm). Then network will be attached at DispVM startup, after restoring savefile, so should behave as any other dynamic network change.

**Comment by talex5** [comment] 2017-11-08 19:57
I believe I have a fix for this now:

https://github.com/mirage/mirage-net-xen/pull/68

The problem seems to be that mirage-firewall re-initialises the shared memory ring, overwriting the RX pages which Linux has placed there. When it wants to send a frame to Linux, it then waits forever for Linux to send it some free pages.

**Closed** 2017-11-09 18:06 UTC
